---
# ######################################################################
# pypiserver docker-compose examples
# ######################################################################
# The below examples illustrate different ways that pypiserver may be
# configured with docker-compose (and by extension, with Docker) to
# serve your python packages.
#
# Most of the configuration options detailed below can be mixed and
# matched as desired.
# ######################################################################

version: "3.3"

services:

    # ##################################################################
    # Default
    # ##################################################################
    # The default configuration serves packages from the /data/packages
    # directory inside the container. This directory is mounted as a
    # volume in the Dockerfile, so it will be persisted, as long as you
    # do not remove it with `docker-compose down -v` or
    # `docker volume rm`.
    # ##################################################################

    pypiserver-default:
        image: pypiserver/pypiserver:latest
        ports:
            - "8080:8080"

   
